# This setup-info was generated:
# https://github.com/DanBurton/stack-setup-info-gen/
# please replace all of this once stack for ghc 8.10 is released
setup-info:
  ghc:
    linux-aarch64:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-aarch64-deb9-linux.tar.xz"
            content-length: 313033012
            sha1: 947f53273ac37a9478739f0f60a78eb30a9fff80
            sha256: c099011e07999db917e797fb5d89c31f075a562556ab99be8ab0accbf2a94db7
    linux32:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-i386-deb9-linux.tar.xz"
            content-length: 215852640
            sha1: 30b28ec4d3b6af5eb3f25668a2567d9ba5c06de0
            sha256: 8b53eef2c827b5f634d72920a93c0c9dd66ea288691a2bfe28def45d3c686ee2
    macosx:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-x86_64-apple-darwin.tar.xz"
            content-length: 192889416
            sha1: 64828a2a2f444cbb5d77d4a15b51a29f03b657f2
            sha256: 65b1ca361093de4804a7e40b3e68178e1ef720f84f743641ec8d95e56a45b3a8
    linux64-gmp4:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-x86_64-centos7-linux.tar.xz"
            content-length: 200974260
            sha1: 43f6680c0d0facf1bcdece57296f03b51119b3ee
            sha256: 0618b94854edc6be5302489df905e627820b71be6b66c950f5e3088fe92df0a1
    linux64:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-x86_64-deb9-linux.tar.xz"
            content-length: 212806588
            sha1: 4d50d074123e686eb0313c90a24959b26131f73c
            sha256: d1cf7886f27af070f3b7dbe1975a78b43ef2d32b86362cbe953e79464fe70761
    linux64-tinfo6:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-x86_64-fedora27-linux.tar.xz"
            content-length: 214693280
            sha1: 3023b3456c50a045e6431de8dbba4e3840c7ab14
            sha256: 3c4cd72b4806045779739e8f5d1658e30e57123d88c2c8966422cdbcae448470
    windows64:
        8.10.1:
            url: "https://downloads.haskell.org/ghc/8.10.1/ghc-8.10.1-x86_64-unknown-mingw32.tar.xz"
            content-length: 427479476
            sha1: 19867b0e4edb18aba8c62f5d44c1d7a67ee6220a
            sha256: 38a3166ea50cccd5bae7e1680eae3aae2b4ae31b61f82a1d8168fb821f43bd67

resolver: ghc-8.10.1
compiler: ghc-8.10.1
compiler-check: match-exact

# This file was automatically generated by 'stack init'
#
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
#
# The location of a snapshot can be provided as a file or url. Stack assumes
# a snapshot provided as a file might change, whereas a url resource does not.
#
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
# resolver: lts-15.13

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
# extra-deps:
# - acme-missiles-0.3
# - git: https://github.com/commercialhaskell/stack.git
#   commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#
extra-deps:
  - git: https://github.com/goldfirere/singletons
    commit: 5f8f2b418989ba0109e965f634f0cf7a850f9191
  - happy-1.19.12
  - syb-0.7.1
  - git: https://github.com/goldfirere/th-desugar
    commit: 5eef50aad9a7db9ad284a427b791891398304fa8
  - fail-4.9.0.0
  - ordered-containers-0.2.2
  - semigroups-0.19.1
  - th-abstraction-0.3.2.0
  - th-lift-0.8.1
  - th-lift-instances-0.1.16
  - th-reify-many-0.1.9
  - th-orphans-0.13.10
  - th-expand-syns-0.4.6.0
  - vector-0.12.1.2
  - safe-0.3.19
  - primitive-0.7.0.1
  - transformers-compat-0.6.5

# Override default flag values for local packages and extra-deps
flags:
  transformers-compat:
    five-three: true

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=2.1"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
